#!/usr/bin/env bash
# submit-smithery-batch.sh — open a Smithery-config PR on every flagship repo.
#
# Smithery indexes any repo that has a `smithery.yaml` at its root. This batches
# the per-repo step from SUBMISSION_CHECKLIST.md: for each generated payload it
# clones the repo, drops in smithery.yaml, commits on a branch, pushes, and opens
# a PR. After merge, Smithery picks the server up automatically.
#
# SAFE BY DEFAULT: dry-run unless you pass SUBMIT=1. Needs Nick's `gh` auth.
#
#   ./scripts/submit-smithery-batch.sh            # dry-run: prints what it WOULD do
#   SUBMIT=1 ./scripts/submit-smithery-batch.sh   # actually push branches + open PRs
#   SUBMIT=1 LIMIT=3 ./scripts/submit-smithery-batch.sh   # do only the first 3 (smoke test)
set -euo pipefail

ORG=CSOAI-ORG
PAYLOAD_DIR="$(cd "$(dirname "$0")/.." && pwd)/dist/distribution/smithery"
WORK="${WORK:-/tmp/smithery-batch}"
BRANCH="chore/smithery-listing"
SUBMIT="${SUBMIT:-0}"
LIMIT="${LIMIT:-0}"

[ -d "$PAYLOAD_DIR" ] || { echo "No payloads at $PAYLOAD_DIR — run: python3.11 scripts/gen-distribution-payloads.py"; exit 1; }
mkdir -p "$WORK"
gh() { command env -u GITHUB_TOKEN -u GH_TOKEN gh "$@"; }   # keyring-token rule
git_() { command env -u GITHUB_TOKEN -u GH_TOKEN git "$@"; }

n=0; done=0
for f in "$PAYLOAD_DIR"/*.yaml; do
  repo="$(basename "$f" .yaml)"; n=$((n+1))
  [ "$LIMIT" != 0 ] && [ "$done" -ge "$LIMIT" ] && { echo "(LIMIT=$LIMIT reached)"; break; }

  if [ "$SUBMIT" != 1 ]; then
    echo "[dry-run $n] would open PR: $ORG/$repo  (drop $(basename "$f") → smithery.yaml)"
    continue
  fi

  echo "==== [$n] $ORG/$repo ===="
  d="$WORK/$repo"
  [ -d "$d" ] || gh repo clone "$ORG/$repo" "$d" -- -q || { echo "  clone failed, skip"; continue; }
  cp "$f" "$d/smithery.yaml"
  ( cd "$d"
    git_ checkout -B "$BRANCH" -q
    git_ add smithery.yaml
    git_ -c user.name='MEOK AI Labs' -c user.email='nicholas@meok.ai' \
        commit -q -m "chore: add smithery.yaml for Smithery (smithery.ai) listing" || { echo "  nothing to commit"; exit 0; }
    git_ push -u origin "$BRANCH" -q
    gh pr create --repo "$ORG/$repo" --head "$BRANCH" --base "$(gh repo view "$ORG/$repo" --json defaultBranchRef -q .defaultBranchRef.name)" \
        --title "chore: list on Smithery (add smithery.yaml)" \
        --body "Adds the generated \`smithery.yaml\` so this MCP server is indexed by https://smithery.ai. Payload generated by scripts/gen-distribution-payloads.py." \
        2>&1 | tail -1
  )
  done=$((done+1))
done
echo
echo "Processed $n repos (acted on $done). Dry-run? SUBMIT=$SUBMIT"
[ "$SUBMIT" != 1 ] && echo "Re-run with SUBMIT=1 to actually open the PRs (LIMIT=3 first to smoke-test)."
